create table accounts (
      Account_ID integer unique generated by default as identity,
      Customer_ID integer,
      Balance bigint,
      Account_Statues varchar(20),
      Account_Type varchar(20),
      Currency varchar(10)
      constraint pk_account_id primary key (account_id),
      constraint fk_cusomer_id foreign key (customer_id) references customers(customer_id)
);


create table customers (
  customer_ID integer unique generated by default as identity,
  First_Name varchar(20),
  Last_Name varchar(20),
  City varchar(20),
  Mobile_No varchar(20),
  Pancard_No varchar(20)
  constraint pk_customer_id primary key (customer_id)
);


create table loans(
  Loan_ID bigint unique NOT NULL,
  customer_id integer NOT NULL,
  Branch_ID int NOT NULL,
  Loan_Amount bigint NOT NULL,
  Date_Issued date,
  Created_At timestamp,
  deleted_at timestamp,
  constraint pk_loan_id primary key (Loan_id),
  constraint fk_customer_id foreign key (customer_id) references customers(customer_id),
  constraint fk_branch_id foreign key (branch_id) references branches(branch_id)
);


create table branches(
  branch_id integer unique generated by default as identity,
  branch_name varchar(20),
  branch_location varchar(20),
  approved_by int,
  created_at timestamp,
  deleted_at timestamp,
  constraint pk_branch_id primary key (branch_id),
  constraint fk_employees foreign key (approved_by) references employees(employee_id);
);


create table transactions(
  transaction_id integer unique generated by default as identity,
  transaction_type varchar(20) NOT NULL,
  from_account_id bigint NOT NULL,
  to_account_id bigint NOT NULL,
  date_issued date,
  amount bigint NOT NULL,
  transaction_medium varchar(20),
  processed_by int,
  created_at timestamp,
  deleted_at timestamp,
  constraint pk_transaction_id primary key (transaction_id),
  constraint fk_from_account foreign key (from_account_id) references accounts(account_id),
  constraint fk_to_account foreign key (to_account_id) references accounts(account_id),
  constraint fk_employees foreign key (processed_by) references employees(employee_id)
);


CREATE TABLE employees (
    employee_id INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    branch_id INTEGER NOT NULL,
    First_Name VARCHAR(100) NOT NULL,
    Last_Name VARCHAR(100) NOT NULL,
    role VARCHAR(50) NOT NULL, 
    hire_date DATE NOT NULL,
    phone VARCHAR(20),
    CONSTRAINT pk_employees PRIMARY KEY (employee_id),
    CONSTRAINT fk_branch_id FOREIGN KEY (branch_id) REFERENCES branches(branch_id)
);